name: final_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the build number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2 # (No update needed, latest)
  cloud_firestore: ^5.5.0
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  email_validator: ^3.0.0
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.0
  geocoding: ^3.0.0
  http: ^1.2.2
  lottie: ^3.1.3
  dartz: ^0.10.1 # (No update needed, latest)
  fab_circular_menu: ^1.0.2 # (No longer maintained, consider alternatives)
  flutter_polyline_points: ^2.1.0
  flutter_rating_stars: ^1.0.3+4 # (No update needed, latest)
  flip_card: ^0.7.0
  flutter_riverpod: ^2.6.1
  khalti_flutter: ^3.0.0
  khalti: ^2.0.0
  cloud_firestore_web: ^4.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/electric-car.png"

flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animassets/mapanimation.json
    - assets/mapicons/
    - assets/fonts/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Italic.ttf
          style: italic
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-Light.ttf
          weight: 200
        - asset: assets/fonts/WorkSans-Thin.ttf
          weight: 300
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 400
        - asset: assets/fonts/WorkSans-ExtraLight.ttf
          weight: 100
